# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-22 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VmResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='名称')),
                ('template_name', models.CharField(blank=True, max_length=50, verbose_name='模板名称')),
                ('system', models.CharField(blank=True, max_length=50, verbose_name='系统')),
                ('specifications', models.CharField(blank=True, max_length=5000, null=True, verbose_name='规格')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='描述')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('vm_num', models.IntegerField(blank=True, null=True, verbose_name='虚机数')),
                ('uuid', models.CharField(blank=True, max_length=256, null=True, verbose_name='uuid')),
                ('vm_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='虚机类型')),
                ('creatdate', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('updatedate', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.ResourcePool')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.VmResource', verbose_name='模板')),
            ],
            options={
                'verbose_name': '虚机资源',
                'verbose_name_plural': '虚机资源',
            },
        ),
    ]
