# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-24 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0002_vmresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='功能名称')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='类型')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='地址')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faconstor.Fun', verbose_name='父节点')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='场景编号')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='场景名称')),
                ('remark', models.CharField(blank=True, max_length=5000, null=True, verbose_name='场景描述')),
                ('business', models.CharField(blank=True, max_length=5000, null=True, verbose_name='影响业务')),
                ('application', models.CharField(blank=True, max_length=5000, null=True, verbose_name='影响应用')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('pnode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faconstor.Scene', verbose_name='父节点')),
                ('process', models.ManyToManyField(to='faconstor.Process')),
            ],
        ),
        migrations.RemoveField(
            model_name='backupresource',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='computerresource',
            name='pool',
        ),
        migrations.DeleteModel(
            name='Joblist',
        ),
        migrations.RemoveField(
            model_name='schduleresource',
            name='pool',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.RemoveField(
            model_name='vmresource',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='vmresource',
            name='template',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='DataSet',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='client_host',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='remark',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='说明'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.DeleteModel(
            name='BackupResource',
        ),
        migrations.DeleteModel(
            name='ClientHost',
        ),
        migrations.DeleteModel(
            name='ComputerResource',
        ),
        migrations.DeleteModel(
            name='DataSet',
        ),
        migrations.DeleteModel(
            name='ResourcePool',
        ),
        migrations.DeleteModel(
            name='SchduleResource',
        ),
        migrations.DeleteModel(
            name='VmResource',
        ),
        migrations.AddField(
            model_name='group',
            name='fun',
            field=models.ManyToManyField(to='faconstor.Fun'),
        ),
        migrations.AddField(
            model_name='processrun',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Scene'),
        ),
    ]
