# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-24 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0003_auto_20180824_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrun',
            name='scene',
        ),
    ]
