# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-08-24 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0006_auto_20180824_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='pnode',
        ),
        migrations.RemoveField(
            model_name='scene',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='scene',
        ),
        migrations.DeleteModel(
            name='Scene',
        ),
    ]
