# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-09 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0019_script_script_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsmanage',
            name='host_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='主机名称'),
        ),
    ]
