# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-18 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0020_hostsmanage_host_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walkthrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('creatuser', models.CharField(blank=True, max_length=50, verbose_name='发起人')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('run_reason', models.CharField(blank=True, max_length=2500, null=True, verbose_name='启动原因')),
                ('note', models.CharField(blank=True, max_length=5000, null=True, verbose_name='记录')),
            ],
        ),
    ]
