# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-18 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0021_walkthrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='walkthrough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Walkthrough'),
        ),
    ]
