# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0022_processrun_walkthrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkthrough',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='演练名称'),
        ),
    ]
