# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-18 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0023_walkthrough_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='process_run',
        ),
        migrations.AddField(
            model_name='invitation',
            name='walkthrough',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Walkthrough'),
        ),
    ]
