# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-09-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0024_auto_20190918_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='walkthrough',
        ),
        migrations.RemoveField(
            model_name='walkthrough',
            name='run_reason',
        ),
        migrations.AddField(
            model_name='walkthrough',
            name='createtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='walkthrough',
            name='purpose',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='演练目的'),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
