# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-06-17 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0034_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
