# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-06-17 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0035_auto_20200617_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(blank=True, null=True, verbose_name='源端client_id')),
                ('client_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='源端client_name')),
                ('info', models.TextField(blank=True, null=True, verbose_name='客户端相关信息')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='系统')),
                ('copy_priority', models.IntegerField(choices=[(1, '主拷贝'), (2, '辅助拷贝')], default=1, null=True, verbose_name='拷贝优先级：1：主拷贝；2：辅助拷贝')),
                ('data_path', models.CharField(default='', max_length=512, null=True, verbose_name='数据文件重定向路径')),
                ('db_open', models.IntegerField(choices=[(1, '是'), (2, '否')], default=1, null=True, verbose_name='是否恢复完成后打开数据库：1：默认打开数据库；2：不打开数据库')),
                ('log_restore', models.IntegerField(choices=[(1, '是'), (2, '否')], default=1, null=True, verbose_name='是否回滚日志')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Target', verbose_name='默认关联终端')),
            ],
        ),
    ]
