# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-06-19 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0039_utilsmanage_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='utils',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.UtilsManage', verbose_name='关联工具'),
        ),
        migrations.AddField(
            model_name='target',
            name='utils',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.UtilsManage', verbose_name='关联工具'),
        ),
    ]
