# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-06-23 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('faconstor', '0043_auto_20200623_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, null=True, verbose_name='流程计划名称')),
                ('remark', models.TextField(default='', null=True, verbose_name='计划说明')),
                ('state', models.CharField(default='', max_length=20, null=True, verbose_name='状态')),
                ('schedule_type', models.IntegerField(choices=[(1, '每日'), (2, '每周'), (3, '每月')], default=1, null=True)),
                ('dj_periodictask', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='djcelery.PeriodicTask', verbose_name='定时任务')),
                ('process', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Process', verbose_name='流程预案')),
            ],
        ),
    ]
