# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-06-27 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0044_processschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskSpaceWeeklyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField(default=0, null=True, verbose_name='MediaID')),
                ('capacity_avaible', models.BigIntegerField(default=0, null=True, verbose_name='可用容量')),
                ('space_reversed', models.BigIntegerField(default=0, null=True, verbose_name='保留空间')),
                ('total_space', models.BigIntegerField(default=0, null=True, verbose_name='总流量')),
                ('extract_time', models.DateTimeField(null=True, verbose_name='取数时间')),
                ('utils', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.UtilsManage', verbose_name='工具')),
            ],
        ),
    ]
