# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-06-27 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0045_diskspaceweeklydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diskspaceweeklydata',
            old_name='space_reversed',
            new_name='space_reserved',
        ),
    ]
