# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-06-28 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0046_auto_20200627_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskspaceweeklydata',
            name='point_tag',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='用以判断同一记录'),
        ),
        migrations.AlterField(
            model_name='diskspaceweeklydata',
            name='total_space',
            field=models.BigIntegerField(default=0, null=True, verbose_name='总容量'),
        ),
    ]
