# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0047_auto_20200628_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsmanage',
            name='config',
            field=models.TextField(default='<root></root>', null=True, verbose_name='主机参数'),
        ),
        migrations.AddField(
            model_name='process',
            name='config',
            field=models.TextField(default='<root></root>', null=True, verbose_name='流程参数'),
        ),
        migrations.AddField(
            model_name='script',
            name='config',
            field=models.TextField(default='<root></root>', null=True, verbose_name='接口参数'),
        ),
    ]
