# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0048_auto_20200706_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='pnode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faconstor.Script', verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='script',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='类型'),
        ),
    ]
