# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-06 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0049_auto_20200706_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='remark',
            field=models.TextField(default='', null=True, verbose_name='节点说明'),
        ),
    ]
