# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-08 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0050_script_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='params',
            field=models.TextField(default='', null=True, verbose_name='脚本内容参数'),
        ),
    ]
