# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-10 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0052_auto_20200709_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptinstance',
            name='utils',
        ),
    ]
