# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-10 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0053_remove_scriptinstance_utils'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptinstance',
            name='utils',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.UtilsManage', verbose_name='工具'),
        ),
    ]
