# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-07-10 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0054_scriptinstance_utils'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scriptrun',
            name='script',
        ),
    ]
