# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-11 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0058_auto_20200810_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbCopyClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbtype', models.TextField(blank=True, null=True, verbose_name='数据库类型')),
                ('hosttype', models.TextField(blank=True, null=True, verbose_name='主机类型')),
                ('info', models.TextField(blank=True, null=True, verbose_name='数据库相关信息')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('hostsmanage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.HostsManage', verbose_name='客户端')),
                ('std', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pri', to='faconstor.DbCopyClient', verbose_name='备库')),
            ],
        ),
    ]
