# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0059_dbcopyclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrun',
            name='browse_job_id',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='copy_priority',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='curSCN',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='data_path',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='db_open',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='log_restore',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='recover_end_time',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='target',
        ),
        migrations.AddField(
            model_name='processrun',
            name='info',
            field=models.TextField(default='', null=True, verbose_name='恢复所需参数,如：target,origin,browse_job_id,data_path,copy_priority,curSCN,db_open'),
        ),
    ]
