# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-17 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0060_auto_20200813_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='pnode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faconstor.Process', verbose_name='父节点'),
        ),
    ]
