# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0061_process_pnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptinstance',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Process', verbose_name='子流程'),
        ),
    ]
