# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-08-25 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0063_auto_20200818_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='process',
            field=models.ManyToManyField(to='faconstor.Process'),
        ),
    ]
