# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-03 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0064_group_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='backprocess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_backprocess_set', to='faconstor.Process', verbose_name='回切流程'),
        ),
        migrations.AddField(
            model_name='process',
            name='hosts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.HostsManage', verbose_name='关联客户端'),
        ),
        migrations.AddField(
            model_name='process',
            name='processtype',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='预案类型'),
        ),
        migrations.AlterField(
            model_name='process',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='客户端类型'),
        ),
    ]
