# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-06 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0065_auto_20200903_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_primary_set', to='faconstor.HostsManage', verbose_name='主数据库'),
        ),
    ]
