# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0067_auto_20200922_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='process',
            old_name='hosts_config',
            new_name='associated_hosts',
        ),
        migrations.AddField(
            model_name='scriptinstance',
            name='associated_hosts',
            field=models.TextField(default='</root>', null=True, verbose_name='关联主机'),
        ),
    ]
