# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0068_auto_20200922_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_hosts', models.TextField(default='</root>', null=True, verbose_name='关联主机')),
                ('config', models.TextField(default='</root>', null=True, verbose_name='流程参数/主机参数')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Process', verbose_name='预案')),
            ],
        ),
    ]
