# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-24 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0069_processinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinstance',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='状态'),
        ),
    ]
