# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0070_processinstance_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinstance',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='流程实例名称'),
        ),
    ]
