# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-25 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0071_processinstance_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processinstance',
            name='associated_hosts',
        ),
    ]
