# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-28 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0074_auto_20200928_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='流程实例名称')),
                ('config', models.TextField(default='</root>', null=True, verbose_name='流程参数/主机参数')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Process', verbose_name='预案')),
            ],
        ),
        migrations.AddField(
            model_name='processschedule',
            name='pro_ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.ProcessInstance', verbose_name='流程预案实例'),
        ),
    ]
