# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-09-30 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0075_auto_20200928_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='pro_ins',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.ProcessInstance', verbose_name='流程实例'),
        ),
    ]
