# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-03 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0076_processrun_pro_ins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrun',
            name='process',
        ),
    ]
