# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0078_auto_20201009_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinstance',
            name='pnode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='faconstor.ProcessInstance', verbose_name='父节点'),
        ),
    ]
