# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-27 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0080_processrun_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='walkthrough',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='pro_ins',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='processrun',
            name='walkthrough',
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='processrun',
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='steprun',
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='walkthrough',
        ),
        migrations.RemoveField(
            model_name='scriptrun',
            name='script',
        ),
        migrations.RemoveField(
            model_name='scriptrun',
            name='steprun',
        ),
        migrations.RemoveField(
            model_name='steprun',
            name='processrun',
        ),
        migrations.RemoveField(
            model_name='steprun',
            name='step',
        ),
        migrations.RemoveField(
            model_name='verifyitems',
            name='step',
        ),
        migrations.RemoveField(
            model_name='verifyitemsrun',
            name='steprun',
        ),
        migrations.RemoveField(
            model_name='verifyitemsrun',
            name='verify_items',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
        migrations.DeleteModel(
            name='ProcessRun',
        ),
        migrations.DeleteModel(
            name='ProcessTask',
        ),
        migrations.DeleteModel(
            name='ScriptRun',
        ),
        migrations.DeleteModel(
            name='StepRun',
        ),
        migrations.DeleteModel(
            name='VerifyItems',
        ),
        migrations.DeleteModel(
            name='VerifyItemsRun',
        ),
        migrations.DeleteModel(
            name='Walkthrough',
        ),
    ]
