# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2020-10-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faconstor', '0081_auto_20201027_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='演练目的')),
                ('current_time', models.DateTimeField(blank=True, null=True, verbose_name='邀请时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('creatuser', models.CharField(blank=True, max_length=50, verbose_name='发起人')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('run_reason', models.TextField(blank=True, null=True, verbose_name='启动原因')),
                ('note', models.TextField(blank=True, null=True, verbose_name='记录')),
                ('walkthroughstate', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('recover_time', models.DateTimeField(blank=True, null=True, verbose_name='指定恢复时间点')),
                ('rto', models.IntegerField(default=0, null=True, verbose_name='流程RTO')),
                ('info', models.TextField(default='', null=True, verbose_name='恢复所需参数,如：target,origin,browse_job_id,data_path,copy_priority,curSCN,db_open')),
                ('pro_ins', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.ProcessInstance', verbose_name='流程实例')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.ProcessSchedule', verbose_name='计划流程')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('senduser', models.CharField(blank=True, max_length=50, null=True, verbose_name='发送人')),
                ('receiveuser', models.CharField(blank=True, max_length=50, null=True, verbose_name='接收人')),
                ('receiveauth', models.CharField(blank=True, max_length=50, null=True, verbose_name='接收角色')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='任务类型')),
                ('content', models.TextField(blank=True, null=True, verbose_name='任务内容')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('result', models.TextField(blank=True, null=True, verbose_name='处理结果')),
                ('explain', models.TextField(blank=True, null=True, verbose_name='处理说明')),
                ('logtype', models.CharField(blank=True, max_length=20, null=True, verbose_name='日志类型')),
                ('processrun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.ProcessRun')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('result', models.TextField(blank=True, null=True, verbose_name='运行结果')),
                ('explain', models.TextField(blank=True, null=True, verbose_name='运行说明')),
                ('runlog', models.TextField(blank=True, null=True, verbose_name='运行日志')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='记录')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.ScriptInstance')),
            ],
        ),
        migrations.CreateModel(
            name='StepRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('operator', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作人')),
                ('parameter', models.CharField(blank=True, max_length=640, null=True, verbose_name='运行参数')),
                ('result', models.TextField(blank=True, null=True, verbose_name='运行结果')),
                ('explain', models.TextField(blank=True, null=True, verbose_name='运行说明')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('note', models.TextField(blank=True, null=True, verbose_name='记录')),
                ('processrun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.ProcessRun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Step')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='确认项')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='状态')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Step')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyItemsRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='状态')),
                ('has_verified', models.CharField(blank=True, max_length=20, null=True, verbose_name='是否确认')),
                ('steprun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.StepRun')),
                ('verify_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faconstor.VerifyItems')),
            ],
        ),
        migrations.CreateModel(
            name='Walkthrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='演练名称')),
                ('createtime', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('starttime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('creatuser', models.CharField(blank=True, max_length=50, verbose_name='发起人')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='状态')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='演练目的')),
                ('note', models.TextField(blank=True, null=True, verbose_name='记录')),
            ],
        ),
        migrations.AddField(
            model_name='scriptrun',
            name='steprun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.StepRun'),
        ),
        migrations.AddField(
            model_name='processtask',
            name='steprun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.StepRun'),
        ),
        migrations.AddField(
            model_name='processtask',
            name='walkthrough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Walkthrough'),
        ),
        migrations.AddField(
            model_name='processrun',
            name='walkthrough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Walkthrough'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='walkthrough',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faconstor.Walkthrough'),
        ),
    ]
